# Generated by Django 4.0.3 on 2022-05-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0002_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cp',
            field=models.IntegerField(default=9200),
        ),
        migrations.AddField(
            model_name='cliente',
            name='provincia',
            field=models.CharField(default='Vitoria', max_length=200),
        ),
    ]
